SET SCHEMA FN4MI0700044;

CREATE TABLE CUSTOMER (
NAME VARCHAR (100) NOT NULL,
PHONE_NUMBER CHAR (10) NOT NULL PRIMARY KEY
);

CREATE TABLE TECHNICIAN (
NAME VARCHAR (100) NOT NULL,
EGN CHAR (10) NOT NULL,
TECHNICIAN_ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
TECHNICIAN_CATEGORY VARCHAR (50) NOT NULL
);

CREATE TABLE APPLIANCE (
NAME VARCHAR (100) NOT NULL,
MODEL VARCHAR (20) NOT NULL,
APPLIANCE_ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 10),
APPLIANCE_CATEGORY VARCHAR (50) NOT NULL,
MANUFACTURER VARCHAR (50) NOT NULL,
YEAR_OF_MANUFACTURE INT CHECK (YEAR_OF_MANUFACTURE > 1900),
CUSTOMER_PHONE_NUMBER CHAR (10) REFERENCES CUSTOMER(PHONE_NUMBER)
);

CREATE TABLE REPAIR (
  APPLIANCE_ID INT NOT NULL CONSTRAINT FK_REPAIR_APP REFERENCES APPLIANCE (APPLIANCE_ID),
  TECHNICIAN_ID INT NOT NULL CONSTRAINT FK_REPAIR_TECH REFERENCES TECHNICIAN (TECHNICIAN_ID),
  DATE DATE,
  PRICE DECIMAL(9, 2),
  CONSTRAINT PK_REPAIR PRIMARY KEY (APPLIANCE_ID, TECHNICIAN_ID)
);
