SET SCHEMA FN4MI0700044;

--readonly
CREATE VIEW V_CUSTOMER_APPLIANCE_INFO (CUSTOMER_NAME, PHONE_NUMBER, APPLIANCE_NAME, APPLIANCE_CATEGORY, APPLIANCE_ID)
AS
SELECT C.NAME as CUSTOMER_NAME, C.PHONE_NUMBER, A.NAME as APPLIANCE_NAME, A.APPLIANCE_CATEGORY, A.APPLIANCE_ID
FROM CUSTOMER C, APPLIANCE A
WHERE C.PHONE_NUMBER = A.CUSTOMER_PHONE_NUMBER;

SELECT *
FROM V_CUSTOMER_APPLIANCE_INFO
WHERE APPLIANCE_CATEGORY = 'Oven';

--updatable
CREATE VIEW V_CUSTOMER_ALL
AS
SELECT NAME, PHONE_NUMBER
FROM CUSTOMER
WHERE NAME LIKE '%Dimitrova';

DROP VIEW V_CUSTOMER_ALL;

SELECT * FROM V_CUSTOMER_ALL;

INSERT INTO V_CUSTOMER_ALL
VALUES ('Elina Dimitrova', '0898901234');



--with check option
CREATE VIEW V_TECHNICIAN_WITH_CK
AS
SELECT NAME, EGN, TECHNICIAN_CATEGORY
FROM TECHNICIAN
WHERE TECHNICIAN_CATEGORY = 'Dishwasher'
WITH CHECK OPTION;

SELECT * FROM V_TECHNICIAN_WITH_CK;

INSERT INTO V_TECHNICIAN_WITH_CK (NAME, EGN, TECHNICIAN_CATEGORY)
VALUES ('Ivan Ivanov', '0123456789', 'Dishwasher');

SELECT * FROM V_TECHNICIAN_WITH_CK;

INSERT INTO V_TECHNICIAN_WITH_CK (NAME, EGN, TECHNICIAN_CATEGORY)
VALUES ('Petar Petrov', '0987654321', 'Oven');
